import type { ChecklistSection } from '../types';
import { C172S_SYSTEMS } from './systems';

const P = C172S_SYSTEMS.engine;

/**
 * The 172S start, which is a genuinely different skill from the 172N's.
 * There is no primer: the boost pump charges the injector lines with the
 * mixture rich, the mixture then goes back to idle cutoff for cranking, and
 * the engine runs on that charge for a few seconds while the pilot advances
 * the mixture. Hesitate and it dies.
 */
export const C172S_CHECKLISTS: readonly ChecklistSection[] = [
  {
    id: 'before-start',
    title: 'Before starting engine',
    items: [
      {
        id: 'seats',
        callout: 'SEATS — ADJUSTED AND LOCKED',
        highlight: 'seatLatch',
        satisfied: (s) => s.controls.bool('seatLatch'),
        why: 'A seat that slides back on the takeoff roll takes the yoke with it. The 172 seat rail has caused real accidents, which is why the lock is checked by hand every time.',
        hint: 'Push the seat latch lever down, beside the seat pan.',
      },
      {
        id: 'belts',
        callout: 'SEAT BELTS — FASTENED',
        highlight: 'seatbelt',
        satisfied: (s) => s.controls.bool('seatbelt'),
        why: 'Belt and shoulder harness on before anything turns. It is also the last moment you can reach the buckle comfortably.',
        hint: 'Click the buckle on the seat beside you.',
      },
      {
        id: 'doors',
        callout: 'CABIN DOORS — CLOSED AND LATCHED',
        highlight: 'cabinDoor',
        satisfied: (s) => s.controls.bool('cabinDoor'),
        why: 'A 172 door that pops open on climb-out is loud, startling and almost impossible to close in flight. The aeroplane flies fine; the surprise is the hazard.',
        hint: 'Pull the door handle on your left to the latched position.',
      },
      {
        id: 'control-lock',
        callout: 'CONTROL LOCK — REMOVED',
        highlight: 'controlLock',
        satisfied: (s) => s.controls.num('controlLock') < 0.3,
        why: 'The lock pins the control column so the surfaces cannot bang about in the wind. It sits right in front of the ignition key so that you physically cannot reach the key without confronting it.',
        hint: 'Pull the red pin out of the control column — drag it downward.',
      },
      {
        id: 'brakes-set',
        callout: 'BRAKES — TEST AND SET',
        highlight: 'parkingBrake',
        satisfied: (s) => s.controls.num('parkingBrake') < 0.3,
        why: 'The engine makes thrust the instant it fires. With the brakes set the aeroplane stays where you left it instead of walking forward into whatever is in front of the nose.',
        hint: 'Pull the parking brake knob out — drag it downward.',
      },
      {
        id: 'fuel-both',
        callout: 'FUEL SELECTOR VALVE — BOTH',
        highlight: 'fuelSelector',
        satisfied: (s) => s.controls.isAt('fuelSelector', 'BOTH'),
        why: 'Injected engines are less forgiving of fuel interruptions than carburetted ones: there is no float bowl holding a reserve, so an engine fed from an empty line quits almost at once.',
        hint: 'Press 6 for the floor view, then click the selector handle round to BOTH.',
      },
      {
        id: 'avionics-off',
        callout: 'AVIONICS POWER SWITCH — OFF',
        highlight: 'avionicsMaster',
        satisfied: (s) => !s.controls.bool('avionicsMaster'),
        why: 'Protects the radios from the starting transient, exactly as on the 172N.',
        hint: 'Switch the AVIONICS rocker down.',
      },
    ],
  },
  {
    id: 'starting',
    title: 'Starting engine',
    items: [
      {
        id: 'throttle-crack',
        callout: 'THROTTLE — OPEN 1/4 INCH',
        highlight: 'throttle',
        satisfied: (s) => s.controls.num('throttle') > 0.06 && s.controls.num('throttle') < 0.28,
        why: 'Enough airflow for the engine to catch and idle, and no more.',
        hint: 'Nudge the black throttle knob in slightly.',
      },
      {
        id: 'master-on',
        callout: 'MASTER SWITCH — ON (BOTH HALVES)',
        highlight: 'masterBattery',
        satisfied: (s) => s.controls.bool('masterBattery') && s.controls.bool('masterAlternator'),
        why: 'The boost pump is electric, so unlike the 172N the master has to be on before you can prime at all.',
        hint: 'Flip both halves of the red MASTER rocker up.',
      },
      {
        id: 'beacon-on',
        callout: 'BEACON — ON',
        highlight: 'beacon',
        satisfied: (s) => s.controls.bool('beacon'),
        why: 'Warns everyone outside that the propeller is about to turn.',
        hint: 'Switch BCN up.',
      },
      {
        id: 'mixture-rich-prime',
        callout: 'MIXTURE — RICH (to prime)',
        highlight: 'mixture',
        satisfied: (s) => s.controls.num('mixture') > 0.95,
        why: 'The mixture control is the valve the boost pump has to push fuel through. With it at idle cutoff the pump simply deadheads and no fuel reaches the injectors.',
        hint: 'Push the red mixture knob fully in.',
      },
      {
        id: 'prime-pump',
        callout: 'AUX FUEL PUMP — ON 3 TO 5 SECONDS, THEN OFF',
        highlight: 'fuelPump',
        satisfied: (s) => s.fuel.primeCharge >= P.primeToCatch && !s.controls.bool('fuelPump'),
        why: 'This is the injected engine\'s prime. Fuel flow rises while the pump runs; three to five seconds fills the injector lines. Much longer and the cylinders are flooded, exactly as with too many primer strokes on a carburetted engine.',
        hint: 'Switch FUEL PUMP up, count three, then switch it back down.',
      },
      {
        id: 'mixture-cutoff-start',
        callout: 'MIXTURE — IDLE CUTOFF',
        highlight: 'mixture',
        satisfied: (s) => s.controls.num('mixture') < 0.1,
        why: 'Counter-intuitive, but correct: the cylinders already hold the prime charge. Cranking with the mixture rich on top of that would flood the engine.',
        hint: 'Pull the red mixture knob fully out again.',
      },
      {
        id: 'prop-clear',
        callout: 'PROPELLER AREA — CLEAR',
        satisfied: (s) => s.pilot.scannedPropArea,
        why: 'Look, shout "CLEAR PROP", and wait. Not a button: you have to actually look.',
        hint: 'Turn your head and look out of the left window, then the right.',
      },
      {
        id: 'crank',
        callout: 'IGNITION SWITCH — START',
        highlight: 'magKey',
        satisfied: (s) => s.engine.state === 'catching' || s.engine.isRunning,
        why: 'The engine will fire on the prime charge alone. It is only good for a few seconds, so the next item has to follow immediately.',
        hint: 'Click the right-hand side of the key round to BOTH, then press and hold there for START.',
      },
      {
        id: 'mixture-advance',
        callout: 'MIXTURE — ADVANCE AS THE ENGINE FIRES',
        highlight: 'mixture',
        satisfied: (s) => s.engine.isRunning && s.controls.num('mixture') > 0.9,
        why: 'The prime charge is burning off. Push the mixture in smoothly and the engine picks up the running fuel supply; leave it and the engine dies a few seconds after it caught. That is the mistake almost everyone makes on their first injected start.',
        hint: 'Push the red mixture knob fully in, now.',
      },
      {
        id: 'oil-pressure',
        callout: 'OIL PRESSURE — CHECK',
        satisfied: (s) => s.engine.isRunning && s.engine.oilPressure > P.oilPressureRedlineLow,
        why: 'Thirty seconds, same rule as every piston engine. No pressure, no engine.',
        hint: 'Watch the OIL PRESS gauge come up into the green.',
      },
      {
        id: 'warm-idle',
        callout: 'THROTTLE — 1000 RPM',
        highlight: 'throttle',
        satisfied: (s) => s.engine.isRunning && s.engine.rpm > 900 && s.engine.rpm < 1250,
        why: 'Warm-up RPM: oil circulating, alternator producing, nothing being shock-loaded.',
        hint: 'Adjust the throttle until the tachometer reads about 1000.',
      },
      {
        id: 'avionics-on',
        callout: 'AVIONICS POWER SWITCH — ON',
        highlight: 'avionicsMaster',
        satisfied: (s) => s.controls.bool('avionicsMaster') && s.engine.isRunning,
        why: 'The transient is over and the radios can come up.',
        hint: 'Switch the AVIONICS rocker up.',
      },
      {
        id: 'ammeter-check',
        callout: 'AMMETER — CHECK CHARGING',
        satisfied: (s) => s.engine.isRunning && s.electrical.alternatorOnline,
        why: 'The alternator should be replacing what the starter took.',
        hint: 'Confirm a charge on the ammeter and no low-voltage light.',
      },
    ],
  },
  {
    id: 'shutdown',
    title: 'Securing the aeroplane',
    phase: 'secure',
    items: [
      {
        id: 'shutdown-throttle',
        callout: 'THROTTLE — 1000 RPM',
        highlight: 'throttle',
        satisfied: (s) => s.engine.rpm > 900 && s.engine.rpm < 1250,
        why: 'Let temperatures settle before stopping.',
        hint: 'Set about 1000 RPM.',
      },
      {
        id: 'shutdown-avionics',
        callout: 'AVIONICS POWER SWITCH — OFF',
        highlight: 'avionicsMaster',
        satisfied: (s) => !s.controls.bool('avionicsMaster'),
        why: 'Protects the radios on the way down as well as on the way up.',
        hint: 'Switch the AVIONICS rocker down.',
      },
      {
        id: 'shutdown-mixture',
        callout: 'MIXTURE — IDLE CUTOFF',
        highlight: 'mixture',
        satisfied: (s) => s.controls.num('mixture') < 0.1 && !s.engine.isRunning,
        why: 'The engine is stopped by starving it of fuel, so nothing combustible is left in the cylinders.',
        hint: 'Pull the mixture fully out and wait for the engine to stop.',
      },
      {
        id: 'shutdown-mags',
        callout: 'IGNITION SWITCH — OFF',
        highlight: 'magKey',
        satisfied: (s) => s.controls.isAt('magKey', 'OFF'),
        why: 'Magnetos make their own spark and do not care about the master switch.',
        hint: 'Click the left-hand side of the key to wind it back to OFF.',
      },
      {
        id: 'shutdown-master',
        callout: 'MASTER SWITCH — OFF',
        highlight: 'masterBattery',
        satisfied: (s) => !s.controls.bool('masterBattery') && !s.controls.bool('masterAlternator'),
        why: 'Anything left on the bus flattens the battery overnight.',
        hint: 'Flip both halves of the red MASTER rocker down.',
      },
    ],
  },
];
