import type { ChecklistSection } from '../types';
import { C172N_SYSTEMS } from './systems';

const P = C172N_SYSTEMS.engine;

/** Every breaker on the panel, for the "circuit breakers — check in" item. */
const BREAKER_IDS = [
  'brkAltField',
  'brkInstLights',
  'brkNavLights',
  'brkBeacon',
  'brkLandLights',
  'brkPitotHeat',
  'brkStrobe',
  'brkTurnCoord',
  'brkFlap',
  'brkRadio1',
  'brkRadio2',
  'brkRadio3',
  'brkXpdr',
  'brkAdf',
  'brkAudio',
  'brkCigar',
  'brkFuelInd',
  'brkLowVolt',
];

/**
 * The C172N checklist, following the POH order, with the reasoning attached.
 * The "why" text is the actual teaching content of this trainer — the steps
 * alone are just a list anyone can read off a card.
 */
export const C172N_CHECKLISTS: readonly ChecklistSection[] = [
  {
    id: 'before-start',
    title: 'Before starting engine',
    items: [
      {
        id: 'seats',
        callout: 'SEATS — ADJUSTED AND LOCKED',
        highlight: 'seatLatch',
        satisfied: (s) => s.controls.bool('seatLatch'),
        why: 'A seat that slides back on the takeoff roll takes the yoke with it. The 172 seat rail has caused real accidents, which is why the lock is checked by hand every time.',
        hint: 'Push the seat latch lever down, beside the seat pan.',
      },
      {
        id: 'belts',
        callout: 'SEAT BELTS — FASTENED',
        highlight: 'seatbelt',
        satisfied: (s) => s.controls.bool('seatbelt'),
        why: 'Belt and shoulder harness on before anything turns. It is also the last moment you can reach the buckle comfortably.',
        hint: 'Click the buckle on the seat beside you.',
      },
      {
        id: 'doors',
        callout: 'CABIN DOORS — CLOSED AND LATCHED',
        highlight: 'cabinDoor',
        satisfied: (s) => s.controls.bool('cabinDoor'),
        why: 'A 172 door that pops open on climb-out is loud, startling and almost impossible to close in flight. The aeroplane flies fine; the surprise is the hazard.',
        hint: 'Pull the door handle on your left to the latched position.',
      },
      {
        id: 'brakes-set',
        callout: 'BRAKES — TEST AND SET',
        highlight: 'parkingBrake',
        satisfied: (s) => s.controls.num('parkingBrake') < 0.3,
        why: 'The engine makes thrust the instant it fires. With the brakes set the aeroplane stays where you left it instead of walking forward into whatever is in front of the nose.',
        hint: 'Pull the parking brake knob out — drag it downward.',
      },
      {
        id: 'fuel-both',
        callout: 'FUEL SELECTOR VALVE — BOTH',
        highlight: 'fuelSelector',
        satisfied: (s) => s.controls.isAt('fuelSelector', 'BOTH'),
        why: 'BOTH feeds the carburettor from the left and right tanks together and is the only position used for takeoff and landing. Leave it OFF and the engine will still start on the fuel already in the float bowl — then quit about ten seconds later.',
        hint: 'Press 6 for the floor view, then click the right-hand side of the selector handle until it points to BOTH.',
      },
      {
        id: 'avionics-off',
        callout: 'AVIONICS POWER SWITCH — OFF',
        highlight: 'avionicsMaster',
        satisfied: (s) => !s.controls.bool('avionicsMaster'),
        why: 'The starter drags the bus voltage down hard and lets it snap back. The avionics master isolates the radios from that spike; it goes off before the start and on again afterwards.',
        hint: 'Switch the AVIONICS rocker down.',
      },
      {
        id: 'breakers-in',
        callout: 'CIRCUIT BREAKERS — CHECK IN',
        satisfied: (s) => BREAKER_IDS.every((id) => s.controls.bool(id)),
        why: 'A breaker left popped from the last flight means that circuit is dead, and you will not find out until you need it. Check them by eye and by feel.',
        hint: 'Push any breaker that is standing proud of the panel back in.',
      },
    ],
  },
  {
    id: 'starting',
    title: 'Starting engine',
    items: [
      {
        id: 'mixture-rich',
        callout: 'MIXTURE — RICH',
        highlight: 'mixture',
        satisfied: (s) => s.controls.num('mixture') > 0.95,
        why: 'Full rich gives the carburettor the fuel/air ratio it needs at cranking speed. Left at idle cutoff the engine will turn over all day and never fire, because no fuel is reaching the cylinders at all.',
        hint: 'Push the red knob all the way in — drag it upward.',
      },
      {
        id: 'carb-heat-cold',
        callout: 'CARBURETTOR HEAT — COLD',
        highlight: 'carbHeat',
        satisfied: (s) => s.controls.num('carbHeat') > 0.95,
        why: 'Carb heat takes unfiltered air from around the exhaust. On the ground that means sucking dust straight into the engine, so it stays cold — in — until you actually need it.',
        hint: 'Push the CARB HEAT handle fully in.',
      },
      {
        id: 'master-on',
        callout: 'MASTER SWITCH — ON (BOTH HALVES)',
        highlight: 'masterBattery',
        satisfied: (s) => s.controls.bool('masterBattery') && s.controls.bool('masterAlternator'),
        why: 'The red rocker is split: BAT connects the battery to the bus, ALT brings the alternator field online. The alternator cannot produce anything until the engine turns, but its field is fed from the battery, so both halves go up together.',
        hint: 'Flip both halves of the red MASTER rocker up.',
      },
      {
        id: 'beacon-on',
        callout: 'BEACON — ON',
        highlight: 'beacon',
        satisfied: (s) => s.controls.bool('beacon'),
        why: 'The rotating beacon is the signal to everyone outside that this propeller is about to move. It goes on before the engine, not after.',
        hint: 'Switch BCN up.',
      },
      {
        id: 'prime',
        callout: 'PRIME — AS REQUIRED (2 TO 6 STROKES)',
        highlight: 'primer',
        satisfied: (s) => s.engine.isWarm || s.fuel.primeCharge >= P.primeToCatch,
        why: 'A cold carburettor cannot atomise enough fuel at 240 RPM, so the primer squirts raw fuel straight into the induction manifold. Two to six strokes cold, none at all when the engine is already warm. Past about six the cylinders are soaked and the engine floods — and clearing a flooded engine is a separate procedure.',
        hint: 'Pull the PRIMER knob fully out and push it fully in. Repeat two or three times.',
      },
      {
        id: 'throttle-crack',
        callout: 'THROTTLE — OPEN 1/4 INCH',
        highlight: 'throttle',
        satisfied: (s) => s.controls.num('throttle') > 0.06 && s.controls.num('throttle') < 0.28,
        why: 'Just enough airflow for the engine to catch and idle. Wide open and it will fire at a high RPM with cold oil that has not reached the bearings yet.',
        hint: 'Nudge the black throttle knob in slightly — a small upward drag.',
      },
      {
        id: 'prop-clear',
        callout: 'PROPELLER AREA — CLEAR',
        satisfied: (s) => s.pilot.scannedPropArea,
        why: 'Look, then shout "CLEAR PROP", then wait. The propeller disc is invisible once it turns and a person standing in it cannot be seen from the left seat. This one is not a button: you have to actually look.',
        hint: 'Turn your head and look out of the left window, then the right — drag the view around.',
      },
      {
        id: 'start',
        callout: 'IGNITION SWITCH — START, RELEASE WHEN RUNNING',
        highlight: 'magKey',
        satisfied: (s) => s.engine.isRunning,
        why: 'Turn the key past BOTH to START and hold it. Let go the moment the engine fires: holding the starter against a running engine grinds it against the ring gear. Ten seconds of cranking is the limit, then let the starter cool.',
        hint: 'Click the right-hand side of the ignition key to step it round to BOTH, then press and hold there for START.',
      },
      {
        id: 'oil-pressure',
        callout: 'OIL PRESSURE — CHECK',
        satisfied: (s) => s.engine.isRunning && s.engine.oilPressure > P.oilPressureRedlineLow,
        why: 'If the needle has not come off the peg within 30 seconds, shut the engine down. An engine running without oil pressure is destroying its bearings while you watch.',
        hint: 'Watch the OIL PRESS gauge in the engine cluster come up into the green.',
      },
      {
        id: 'warm-idle',
        callout: 'THROTTLE — 1000 RPM',
        highlight: 'throttle',
        satisfied: (s) => s.engine.isRunning && s.engine.rpm > 900 && s.engine.rpm < 1250,
        why: 'A warm-up RPM that keeps oil circulating and the alternator producing, without shock-cooling or racing a cold engine.',
        hint: 'Adjust the throttle until the tachometer reads about 1000.',
      },
      {
        id: 'avionics-on',
        callout: 'AVIONICS POWER SWITCH — ON',
        highlight: 'avionicsMaster',
        satisfied: (s) => s.controls.bool('avionicsMaster') && s.engine.isRunning,
        why: 'The starting transient is over, so the radios can safely come up.',
        hint: 'Switch the AVIONICS rocker up.',
      },
      {
        id: 'ammeter-check',
        callout: 'AMMETER — CHECK CHARGING',
        satisfied: (s) => s.engine.isRunning && s.electrical.alternatorOnline,
        why: 'The needle should sit slightly on the charge side, replacing what the starter just took out of the battery. A discharge here means the alternator is not carrying the load and the flight is over before it starts.',
        hint: 'Confirm the ammeter is showing a charge and the low-voltage light is out.',
      },
    ],
  },
  {
    id: 'shutdown',
    title: 'Securing the aeroplane',
    phase: 'secure',
    items: [
      {
        id: 'shutdown-throttle',
        callout: 'THROTTLE — 1000 RPM',
        highlight: 'throttle',
        satisfied: (s) => s.engine.rpm > 900 && s.engine.rpm < 1250,
        why: 'A short period at a stable low RPM lets cylinder head temperatures settle before the engine stops.',
        hint: 'Set about 1000 RPM on the tachometer.',
      },
      {
        id: 'shutdown-avionics',
        callout: 'AVIONICS POWER SWITCH — OFF',
        highlight: 'avionicsMaster',
        satisfied: (s) => !s.controls.bool('avionicsMaster'),
        why: 'Same reasoning as the start: protect the radios from what the electrical system does as it is shut down.',
        hint: 'Switch the AVIONICS rocker down.',
      },
      {
        id: 'shutdown-mixture',
        callout: 'MIXTURE — IDLE CUTOFF',
        highlight: 'mixture',
        satisfied: (s) => s.controls.num('mixture') < 0.1 && !s.engine.isRunning,
        why: 'A piston engine is stopped by starving it of fuel, not by switching off the ignition. Cutting the mixture leaves no combustible charge in the cylinders, so the propeller cannot fire the engine if someone moves it later.',
        hint: 'Pull the red mixture knob fully out and wait for the engine to stop.',
      },
      {
        id: 'shutdown-mags',
        callout: 'IGNITION SWITCH — OFF',
        highlight: 'magKey',
        satisfied: (s) => s.controls.isAt('magKey', 'OFF'),
        why: 'Magnetos generate their own spark and do not care whether the battery master is on. Until the key is at OFF and the ignition is grounded, the propeller is live.',
        hint: 'Click the left-hand side of the ignition key to wind it back to OFF.',
      },
      {
        id: 'shutdown-master',
        callout: 'MASTER SWITCH — OFF',
        highlight: 'masterBattery',
        satisfied: (s) => !s.controls.bool('masterBattery') && !s.controls.bool('masterAlternator'),
        why: 'Anything left on the bus will flatten the battery overnight.',
        hint: 'Flip both halves of the red MASTER rocker down.',
      },
    ],
  },
];
